linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - ineffassign
    - gosimple
    - goconst
    - bodyclose
    - whitespace
  revive:
    rules:
      - name: var-naming
        severity: warning
        disabled: false