name: Main Pipeline
on: [push, pull_request]
jobs:
  golangci:
    name: Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workdir: ['rate-app', 'logs-consumer']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
          working-directory: ${{ matrix.workdir }}

  build-and-tests:
    name: Build and tests
    runs-on: ubuntu-latest
    needs: golangci
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: Build
        working-directory: ./rate-app
        run: go build -v ./...
      - name: Test
        working-directory: ./rate-app/internal
        run: go test -v ./...
      - name: Test arch
        working-directory: ./rate-app/tests/architecture
        run: go test -v ./...

  e2e:
    name: e2e tests
    runs-on: ubuntu-latest
    needs:
      - build-and-tests
    steps:
      - uses: actions/checkout@v3
      - name: Lunch server
        run: docker compose up -d
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: Run E2E tests
        working-directory: ./rate-app/tests/e2e
        run: go test -v ./...