name: Main Pipeline
on: [push, pull_request]
jobs:
  golangci:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53
  build:
    name: Build and tests
    runs-on: ubuntu-latest
    needs: golangci
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'
          cache: false
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
